apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend
  namespace: aws-study-board
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      
      containers:
      - name: board-frontend
        image: 566644819993.dkr.ecr.ap-northeast-2.amazonaws.com/project_nginx:v2
        ports:
        - containerPort: 80
        
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 2
        
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        
        
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "100m"  
            memory: "128Mi"
